import {DefaultView} from "@/app/models/WebsiteView";

export const SiteAudit: DefaultView = {
    id: "site-audit",
    title: "Site Audit",
    weight: 1,
    enabled: true,
    isDefault: true,
    dataSources: [
        {
            "id" : "monit_site_audit",
            "fields" : [
                "monit_site_audit_cron_cron_enabled",
                "monit_site_audit_content_content_vocabularies",
                "monit_site_audit_content_content_vocabularies_unused",
                "monit_site_audit_content_content_taxonomy",
                "monit_site_audit_content_content_field_unused",
                "monit_site_audit_content_content_field_instances",
                "monit_site_audit_content_content_entity_types",
                "monit_site_audit_content_content_enity_types_unused",
                "monit_site_audit_content_content_duplicate_titles",
                "monit_site_audit_content_content_field_count",
                "monit_site_audit_content_content_field_enabled",
                "monit_site_audit_codebase_codebase_sizeall",
                "monit_site_audit_cache_cache_preprocess_js",
                "monit_site_audit_cache_cache_preprocess_css",
                "monit_site_audit_cache_cache_page_expire",
                "monit_site_audit_cache_cache_default_bins",
                "monit_site_audit_cache_cache_bins_used",
                "monit_site_audit_cache_cache_bins_all",
                "monit_site_audit_block_block_enabled",
                "monit_site_audit_best_practices_best_practices_sites_superflouous",
                "monit_site_audit_best_practices_best_practices_sites_default",
                "monit_site_audit_best_practices_best_practices_sites",
                "monit_site_audit_best_practices_best_practices_settings",
                "monit_site_audit_best_practices_best_practices_services",
                "monit_site_audit_best_practices_best_practices_multisite",
                "monit_site_audit_best_practices_best_practices_folder_structure",
                "monit_site_audit_best_practices_best_practices_fast_404",
                "monit_site_audit_cron_cron_last",
                "monit_site_audit_database_database_size",
                "monit_site_audit_database_database_collation",
                "monit_site_audit_database_database_engine",
                "monit_site_audit_database_database_fragmentation",
                "monit_site_audit_database_database_row_count",
                "monit_site_audit_extensions_extensions_count",
                "monit_site_audit_extensions_extensions_dev",
                "monit_site_audit_extensions_extensions_duplicate",
                "monit_site_audit_extensions_extensions_unrecommended",
                "monit_site_audit_security_security_menu_router",
                "monit_site_audit_status_status_system",
                "monit_site_audit_users_users_count_all",
                "monit_site_audit_users_users_who_is_number_one",
                "monit_site_audit_users_users_blocked_number_one",
                "monit_site_audit_users_users_count_blocked",
                "monit_site_audit_users_users_roles_list",
                "monit_site_audit_views_views_enabled",
                "monit_site_audit_views_views_count",
                "monit_site_audit_views_views_cache_output",
                "monit_site_audit_views_views_cache_results",
                "monit_site_audit_watchdog_watchdog_syslog",
                "monit_site_audit_watchdog_watchdog_enabled"
            ]
        }
    ]
}