# MonitDev App Docker Image Workflow
# Repository: https://github.com/MonitDev/app
#
# Maintainer: Abdulrahman Ghodayah

name: MonitDev App Docker Image Workflow

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha'

env:
  IMAGE_NAME: monitdev-app

jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Echo release and branch
        run: echo "Release = ${{ github.ref_name }}  |  Branch = ${{ github.event.base_ref }}"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.CR_ENDPOINT }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{raw}}
      - name: Log into dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR_ENDPOINT }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      # Below secrets and step will only run for PRODUCTION, when release tag doesn't contain 'beta' or 'alpha'
      - name: Build & Push
        if: contains(github.ref_name , 'beta') == false && contains(github.ref_name , 'alpha') == false && github.event.base_ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          build-args: |
            version=${{ steps.meta.outputs.tags }}
          tags: ${{ steps.meta.outputs.tags }}
      # Below secrets and step will only run for STAGING (BETA), when release tag contains 'beta'
      - name: Build & Push
        if: contains(github.ref_name , 'beta') == true
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          build-args: |
            version=${{ steps.meta.outputs.tags }}
          tags: ${{ steps.meta.outputs.tags }}
      # Below secrets and step will only run for DEVELOPMENT (ALPHA), when release tag contains 'alpha'
      - name: Build & Push
        if: contains(github.ref_name , 'alpha') == true
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          build-args: |
            version=${{ steps.meta.outputs.tags }}
          tags: ${{ steps.meta.outputs.tags }}
